# Generated by Django 5.2.5 on 2025-08-21 21:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('property_type', models.CharField(choices=[('house', 'Casa'), ('apartment', 'Apartamento'), ('office', 'Oficina'), ('land', 'Terreno'), ('commercial', 'Local Comercial'), ('warehouse', 'Bodega')], max_length=20, verbose_name='Tipo de Propiedad')),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('sold', 'Vendida'), ('rented', 'Arrendada'), ('reserved', 'Reservada')], default='available', max_length=20, verbose_name='Estado')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio')),
                ('price_per_sqm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio por m²')),
                ('bedrooms', models.PositiveIntegerField(default=0, verbose_name='Habitaciones')),
                ('bathrooms', models.PositiveIntegerField(default=0, verbose_name='Baños')),
                ('parking_spaces', models.PositiveIntegerField(default=0, verbose_name='Espacios de Parqueo')),
                ('area_sqm', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Área (m²)')),
                ('floor', models.PositiveIntegerField(blank=True, null=True, verbose_name='Piso')),
                ('total_floors', models.PositiveIntegerField(blank=True, null=True, verbose_name='Total de Pisos')),
                ('address', models.CharField(max_length=500, verbose_name='Dirección')),
                ('neighborhood', models.CharField(max_length=100, verbose_name='Barrio')),
                ('city', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitud')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitud')),
                ('has_garden', models.BooleanField(default=False, verbose_name='Jardín')),
                ('has_pool', models.BooleanField(default=False, verbose_name='Piscina')),
                ('has_balcony', models.BooleanField(default=False, verbose_name='Balcón')),
                ('has_elevator', models.BooleanField(default=False, verbose_name='Ascensor')),
                ('is_furnished', models.BooleanField(default=False, verbose_name='Amueblado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Destacada')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Agente')),
            ],
            options={
                'verbose_name': 'Propiedad',
                'verbose_name_plural': 'Propiedades',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('contact_type', models.CharField(choices=[('inquiry', 'Consulta'), ('visit', 'Solicitud de Visita'), ('offer', 'Oferta'), ('other', 'Otro')], default='inquiry', max_length=20, verbose_name='Tipo de Contacto')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Procesado')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.property', verbose_name='Propiedad')),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='properties/', verbose_name='Imagen')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Descripción')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Imagen Principal')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property', verbose_name='Propiedad')),
            ],
            options={
                'verbose_name': 'Imagen de Propiedad',
                'verbose_name_plural': 'Imágenes de Propiedades',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.property', verbose_name='Propiedad')),
            ],
            options={
                'verbose_name': 'Favorito',
                'verbose_name_plural': 'Favoritos',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'property')},
            },
        ),
    ]
