# Generated by Django 5.2.5 on 2025-09-18 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_lote_precio_metro_cuadrado'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
