# Generated by Django 5.2.5 on 2025-10-01 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_lote_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='transaccion',
            name='cliente',
        ),
        migrations.AddField(
            model_name='solicitud',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.usuario'),
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
