# Generated by Django 5.2.5 on 2025-10-04 01:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_cliente_rename_usuario_usuario_perfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaccion',
            name='creado_en',
        ),
        migrations.AddField(
            model_name='transaccion',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='metodo_pago',
            field=models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('tarjeta_debito', 'Tarjeta Debito'), ('tarjeta_credito', 'Tarjeta Credito')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='monto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='estadolote',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='historialestado',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lote',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rolusuario',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tiposolicitud',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='tipo',
            field=models.CharField(blank=True, choices=[('RESERVA', 'Reserva'), ('VENTA', 'Venta'), ('CUOTA', 'Cuota')], max_length=8, null=True),
        ),
        migrations.CreateModel(
            name='Cliente_Comprador',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_compra', models.DateTimeField(auto_now_add=True)),
                ('tipo_relacion', models.CharField(choices=[('Propietario', 'Propietario'), ('reservante', 'Reservante'), ('copropietario', 'Copropietario')], max_length=20)),
                ('porcentaje_participacion', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras', related_query_name='compra', to='database.cliente')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras', related_query_name='compra', to='database.lote')),
            ],
        ),
        migrations.AddField(
            model_name='lote',
            name='cliente_comprador',
            field=models.ManyToManyField(blank=True, related_name='lotes', through='database.Cliente_Comprador', to='database.cliente'),
        ),
        migrations.CreateModel(
            name='Credito',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('monto_base', models.DecimalField(decimal_places=2, max_digits=12)),
                ('interes', models.PositiveIntegerField(default=0)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('num_cuotas_totales', models.PositiveIntegerField()),
                ('num_cuotas_pagadas', models.PositiveIntegerField(default=0)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('estado_credito', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('cancelado', 'Cancelado')], max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.cliente')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.lote')),
            ],
        ),
        migrations.AddField(
            model_name='transaccion',
            name='credito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.credito'),
        ),
    ]
