# Generated by Django 5.2.5 on 2025-10-02 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_cliente_rename_usuario_usuario_perfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente_Comprador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_compra', models.DateTimeField(auto_now_add=True)),
                ('tipo_relacion', models.CharField(choices=[('comprador', 'Comprador'), ('reservante', 'Reservante'), ('copropietario', 'Copropietario')], max_length=20)),
                ('porcentaje_participacion', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente_comprador_relaciones', related_query_name='cliente_comprador_relacion', to='database.cliente')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente_comprador_relaciones', related_query_name='cliente_comprador_relacion', to='database.lote')),
            ],
        ),
        migrations.AddField(
            model_name='lote',
            name='cliente_comprador',
            field=models.ManyToManyField(blank=True, related_name='lotes', through='database.Cliente_Comprador', to='database.cliente'),
        ),
    ]
