# Generated by Django 5.2.5 on 2025-10-10 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_remove_transaccion_creado_en_transaccion_fecha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
