# Generated by Django 5.2.5 on 2025-10-23 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_cliente_fecha_nacimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
