# Generated by Django 5.2.5 on 2025-10-27 19:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_cliente_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lote',
            name='cliente_comprador',
        ),
        migrations.RemoveField(
            model_name='transaccion',
            name='usuario',
        ),
        migrations.AddField(
            model_name='transaccion',
            name='cliente',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='database.cliente'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='relacion_cliente_lote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tipo_relacion', models.CharField(choices=[('Propietario', 'Propietario'), ('reservante', 'Reservante'), ('copropietario', 'Copropietario'), ('declinado', 'Declinado')], max_length=20)),
                ('porcentaje_participacion', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras', related_query_name='compra', to='database.cliente')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras', related_query_name='compra', to='database.lote')),
            ],
        ),
        migrations.AddField(
            model_name='lote',
            name='relacion_cliente_lote',
            field=models.ManyToManyField(blank=True, related_name='lotes', through='database.relacion_cliente_lote', to='database.cliente'),
        ),
        migrations.DeleteModel(
            name='Cliente_Comprador',
        ),
    ]
