# Generated by Django 5.2.5 on 2025-10-27 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0010_remove_lote_cliente_comprador_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='tipo',
            field=models.CharField(blank=True, choices=[('RESERVA', 'Reserva'), ('VENTA', 'Venta'), ('CUOTA', 'Cuota'), ('AMORTIZACION', 'Amortización')], max_length=12, null=True),
        ),
    ]
