# Generated by Django 5.2.5 on 2025-10-27 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0011_alter_transaccion_tipo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EstadoLote',
            new_name='Estado_Lote',
        ),
        migrations.RenameModel(
            old_name='HistorialEstado',
            new_name='Historial_Estado',
        ),
        migrations.RenameModel(
            old_name='RolUsuario',
            new_name='Rol_Usuario',
        ),
    ]
