# Generated by Django 5.2.5 on 2025-11-11 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0013_cliente_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='estado_financiero_actual',
            field=models.CharField(blank=True, choices=[('al_dia', 'Al día'), ('deudor', 'Deudor'), ('conciliado', 'Conciliado')], max_length=20, null=True),
        ),
    ]
