# Generated by Django 5.2.5 on 2025-11-17 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0014_cliente_estado_financiero_actual'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='fecha_conciliacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='montos_pendientes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
