# Generated by Django 5.2.5 on 2025-11-19 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0015_cliente_fecha_conciliacion_cliente_montos_pendientes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='montos_pendientes',
            new_name='meses_deuda',
        ),
        migrations.AddField(
            model_name='cliente',
            name='monto_cuota',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='estado_financiero_actual',
            field=models.CharField(blank=True, choices=[('al dia', 'Al dia'), ('deudor', 'Deudor'), ('conciliado', 'Conciliado')], max_length=20, null=True),
        ),
    ]
